
import com.sun.imageio.plugins.common.I18N;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alumno
 */
public class acceso extends javax.swing.JFrame {
    String ruta ="";
    URL url = null;
    ImageIcon icon = null;

    /**
     * Creates new form acceso
     */
    public acceso() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblOpcion = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jLimg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstListado = new javax.swing.JList<>();
        btnLista = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblOpcion.setText("       Selecciona");

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "JAVA ", "Phyton ", "php ", " " }));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });

        lstListado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Opcion 1", "Opcion 2", "Opcion 3", "Opcion 4", "Opcion 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstListado);

        btnLista.setText("Entrar");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbOpciones, 0, 107, Short.MAX_VALUE)
                    .addComponent(lblOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLimg, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLista)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLimg, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLista)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        // TODO add your handling code here:
        int op = jcbOpciones.getSelectedIndex();
        String cadena = jcbOpciones.getSelectedItem().toString();
                
        switch (op){
              case 0: JOptionPane.showMessageDialog(null,
                    "Nada",
                    "Opcion seleccionada",
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Seleccionaste la opccion 1");
                    
                    
                     break;
            
            case 1: this.mostrarImagen("/img/1.png",op+1,cadena);
                    
                    /*JOptionPane.showMessageDialog(null,
                    "Numero 1",
                    "Opcion seleccionada",
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Seleccionaste la opccion 1");
                    jLimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png")));
                    */
                     break;
                    
            case 2: this.mostrarImagen("/img/2.png",op+1,cadena);
                    /*JOptionPane.showMessageDialog(null,
                    "Numero 2",
                    "Opcion seleccionada",
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Seleccionaste la opccion 2");
                    jLimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png")));
                    */
                    break;
                    
             case 3: this.mostrarImagen("/img/3.png",op+1,cadena);
                 /*JOptionPane.showMessageDialog(null,
                    "Numero 3",
                    "Opcion seleccionada",
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Seleccionaste la opccion 3");
                    jLimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png")));
                    */
                    break;
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        int opc = lstListado.getSelectedIndex();
        
        switch (opc){
            case -1:JOptionPane.showMessageDialog(null, "no ha seleccionado nada",
                                                          "mensaje",
                                         JOptionPane.INFORMATION_MESSAGE);
            break;
            case 0:
            case 1: 
            case 2:
            case 3:    
            case 4: mostrarCuadro(opc+1);
            break;
            
        
        
        }
        //JOptionPane.showMessageDialog(null, "Opcion No:" + opc,
          //                                                  "Opcion Seleccionada",
          //                                 JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mostrarCuadro(int op){
        JOptionPane.showMessageDialog(null, "Opcion No:" + op,
                                                           "Opcion Seleccionada",
                                         JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceso().setVisible(true);
            }
        });
    }
    
    public void mostrarImagen(String urlImagen,
                                int opcion,
                                String cad){
    ruta = urlImagen;
    url= this.getClass().getResource(urlImagen);
    icon=new ImageIcon(url);
    jLimg.setIcon(icon);
    jLimg.setText("Opcion: " + opcion + " Texto: " + cad);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLista;
    private javax.swing.JLabel jLimg;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel lblOpcion;
    private javax.swing.JList<String> lstListado;
    // End of variables declaration//GEN-END:variables
}
